// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcAkira.Shared.Data;

#nullable disable

namespace MvcAkira.Shared.Migrations
{
    [DbContext(typeof(AkiraDbContext))]
    partial class AkiraDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MvcAkira.Shared.Entities.MejaBiodata", b =>
                {
                    b.Property<string>("BiodataCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BiodataAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BiodataBorn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BiodataCreatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BiodataFullname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BiodataPhone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("BiodataSoftdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("BiodataUpdatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("JabatanCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PenggunaCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokoCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("BiodataCode");

                    b.HasIndex("JabatanCode");

                    b.HasIndex("PenggunaCode")
                        .IsUnique();

                    b.HasIndex("TokoCode");

                    b.ToTable("MejaBiodata");
                });

            modelBuilder.Entity("MvcAkira.Shared.Entities.MejaHakakses", b =>
                {
                    b.Property<string>("HakaksesCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("HakaksesCreate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("HakaksesCreatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("HakaksesDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("HakaksesLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("HakaksesRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("HakaksesSoftdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("HakaksesUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("HakaksesUpdatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PenggunaCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("HakaksesCode");

                    b.HasIndex("TargetCode");

                    b.HasIndex("PenggunaCode", "TargetCode")
                        .IsUnique();

                    b.ToTable("MejaHakakses");
                });

            modelBuilder.Entity("MvcAkira.Shared.Entities.MejaJabatan", b =>
                {
                    b.Property<string>("JabatanCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("JabatanCreatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("JabatanName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("JabatanSoftdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("JabatanUpdatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("JabatanCode");

                    b.ToTable("MejaJabatan");
                });

            modelBuilder.Entity("MvcAkira.Shared.Entities.MejaKeuangan", b =>
                {
                    b.Property<string>("KeuanganCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeuanganCreatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeuanganDeskripsi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeuanganJudul")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KeuanganNominal")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("KeuanganSoftdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("KeuanganStatus")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeuanganTempat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeuanganUpdatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeuanganWaktucatat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PenggunaCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokoCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("KeuanganCode");

                    b.HasIndex("KeuanganWaktucatat");

                    b.HasIndex("PenggunaCode");

                    b.HasIndex("TokoCode");

                    b.ToTable("MejaKeuangan");
                });

            modelBuilder.Entity("MvcAkira.Shared.Entities.MejaLog", b =>
                {
                    b.Property<string>("LogCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogCreatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogMencatat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogNewvalue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogOldvalue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogPelaku")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("LogSoftdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("LogTarget")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogUpdatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("LogCode");

                    b.HasIndex("LogCreatedat");

                    b.HasIndex("LogMencatat");

                    b.HasIndex("LogPelaku");

                    b.ToTable("MejaLog");
                });

            modelBuilder.Entity("MvcAkira.Shared.Entities.MejaPengguna", b =>
                {
                    b.Property<string>("PenggunaCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PenggunaCreatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PenggunaEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PenggunaNonaktif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("PenggunaPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("PenggunaSoftdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("PenggunaUpdatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("PenggunaCode");

                    b.HasIndex("PenggunaEmail")
                        .IsUnique();

                    b.ToTable("MejaPengguna");
                });

            modelBuilder.Entity("MvcAkira.Shared.Entities.MejaTarget", b =>
                {
                    b.Property<string>("TargetCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetCreatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetKeterangan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetSoftdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TargetUpdatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("TargetCode");

                    b.ToTable("MejaTarget");
                });

            modelBuilder.Entity("MvcAkira.Shared.Entities.MejaToko", b =>
                {
                    b.Property<string>("TokoCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokoAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokoCreatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokoEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokoName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokoPhone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("TokoSoftdeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("TokoUpdatedat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("TokoCode");

                    b.ToTable("MejaToko");
                });
#pragma warning restore 612, 618
        }
    }
}
